export const comments = {
  EN: [
    {
      author_name: "Inna Yoshchenko",
      author_url:
        "https://www.google.com/maps/contrib/105358473571536841498/reviews",
      language: "en",
      original_language: "en",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "3 months ago",
      text: "Thanks a lot to the doctor for fixing my retainer urgently without an appointment. Highly recommended!",
      time: 1681399532,
      translated: false,
    },
    {
      author_name: "Fatma Khenissi",
      author_url:
        "https://www.google.com/maps/contrib/102584165715243815571/reviews",
      language: "en",
      original_language: "en",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "a year ago",
      text: "Did my braces and very happy with the results 😊",
      time: 1656696668,
      translated: false,
    },
    {
      author_name: "Marwa Ihssane",
      author_url:
        "https://www.google.com/maps/contrib/100072454467928026166/reviews",
      language: "en",
      original_language: "en",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "a year ago",
      text: "I started with Doctor Emre January 2021. I already had the braces in my upper teeth but he removed them and started anew. Now in March 2022 I had my braces removed as my treatment has finished. I can safely say that Dr Emre is so professional and so good at his job. I love how my teeth are looking now. Every session he'd surprise me with some new technique that would fasten my treatment. I trusted him with everything he's done to my teeth and I am very glad I did.\nP.S. he speaks English alright, understands and can explain to you the whole process.",
      time: 1648406429,
      translated: false,
    },
    {
      author_name: "serkan üçpınar",
      author_url:
        "https://www.google.com/maps/contrib/113660381771308757250/reviews",
      language: "en-US",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "5 months ago",
      text: "I cannot thank Emre Bey and Aslı enough. Professional and awesome people. I had an impacted tooth, and I don't want to be photographed because my lower teeth are visible when I smile, my mouth was closed in every photograph. I called a doctor for 5 years and I always postponed it because I was scared. Emre Bey gave me confidence. They have a very warm environment. With braces treatment for 1.5 years and Emre Bey's operation, which I did not feel any pain, I achieved the image I dreamed of. Now I say it's good, I got to know you well. 🙏",
      time: 1677347446,
      translated: true,
    },
    {
      author_name: "Menekse Boz",
      author_url:
        "https://www.google.com/maps/contrib/104603087473060808709/reviews",
      language: "en-US",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "3 months ago",
      text: "First of all, I would like to thank my dear teacher Emre, Aslı and Ms. Yasemin.\nIn the orthodontic treatment that I started due to the shifting of the middle center of my upper teeth; Emre Bey's correct treatment method, professional and meticulous work and perfectionism, I achieved very successful results after fourteen months.\nWhen I went to the first meeting, when I saw Emre Bey's dominance and professionalism, I left that clinic with a happy smile, feeling confident that I made the right decision as a result of my treatment.\nMs. Aslı is a wonderful dentist with her lightness of hand, smiling face and always encouraging and motivating speeches.\nIf you want to have both healthy and aesthetic teeth, you can trust and entrust your teeth without looking for other options. The only Orthodontist Specialist Emre METİN and Dentist Aslıhan METİN I can recommend to everyone with a clear heart.",
      time: 1682106522,
      translated: true,
    },
  ],
  TR: [
    {
      author_name: "Menekse Boz",
      author_url:
        "https://www.google.com/maps/contrib/104603087473060808709/reviews",
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "3 ay önce",
      text: "Değerli Emre Hocaa, Aslı Hoca ve Yasemin Hanım’ a öncelikle canı gönülden çok teşekkür ediyorum.\nÜst dişlerimin orta merkezinin kayması nedeniyle başladığım ortodonti tedavisinde; Emre Bey’ in doğru tedavi yöntemi, profosyonel ve titiz çalışması ve mükemmeliyetçiliği ile on dört ay sonunda çok başarılı sonuçlar elde ettim.\nİlk görüşmeye gittiğimde Emre Bey’ in işine olan hakimiyeti ve profosyonelliğini görünce o kapıdan ne kadar emin olarak çıktıysam, tedavimin sonucunda da o klinikten ne kadar doğru karar verdiğime tekrardan emin olup, mutlu gülücüklerle ayrıldım 😊\nAslı Hanım elinin hafifliği, güler yüzlülüğü, her zaman moral verici ve motive edici konuşmaları ile harika bir diş hekimi.\nHem sağlıklı hem de estetik dişlere sahip olmak istiyorsanız başka tercihler aramadan gözünüz kapalı güvenebilir, dişlerinizi emanet edebilirsiniz. Herkese gönlüm rahat bir şekilde tavsiye edebileceğim tek  Ortodonti Uzmanı Emre METİN ve Diş Hekimi Aslıhan METİN.",
      time: 1682106522,
      translated: false,
    },
    {
      author_name: "P...",
      author_url: null,
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      text: "Dişlerimde şekil bozulma başladığı için kendisine muayene oldum. Muayene sonucunda çapraz kapanış bozukluğu olduğunu ve ortodontik tedavi görmem gerektiğini belirtti. Kapaklı braket ile daha hızlı ve uygun tedavi gerçekleştireceğini söyledi. Tedaviye başladık bu süreçte tedavim bittiğinde bana uyguladığı extra tedavi için minnet duyuyorum. 2 tane implant yaptıracaktım. Kendisi 1 implanta düşürebileceğini ve tel ile bunu mümkün kılacağını söyledi. İnsanın kendi dişi gibi hiçbir tedavinin olmayacağını söyledi. Böylece tedavi sürecim uzadı, ben tellerimi çok sevdiğim ve kullanışlı olduğu için hiç çıkartmak istemiyordum. Her istediğimi rahatlıkla yedim:-) Hiçbir mahrumiyet yaşamadan inci gibi sıra sıra dişlerime kavuştum. Tellerim dün çıktı aynaya bakmadım. Sanki başka birinin dişleriydi. Kendisi inanılmaz derecede mükemmeliyetçi ve estetiğe düşkün olduğu için en güzelini yapıyor. Diş estetisyeni diyebilirim. Kendisine çok teşekkür ederim. Böyle bir tedavi düşünüyorsanız muhakkak iletişime geçin. Gönül rahatlığıyla kendisine güvenebilirsiniz.",
      time: 1575147600,
      translated: false,
    },
    {
      author_name: "Nurdan Akkuş",
      author_url:
        "https://www.google.com/maps/contrib/103450762530276637197/reviews",
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "2 ay önce",
      text: "Saygideger Emre Bey ve Aslı Hanım mesleklerinde en iyilerden. Kızıma sonucu harika olan bir tel tedavisi uyguladılar. Güler yüzünüz sevecenliğiniz bizimle ilgilendiğiniz için sizlere ve Yasemin hanima da teşekkürler...",
      time: 1705436462,
      translated: false,
    },
    {
      author_name: "Elif",
      author_url:
        "https://www.google.com/maps/contrib/103520482178627167905/reviews",
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "3 ay önce",
      text: "doktorum tedavimi en iyi şekilde başladı ve bitirdi kendisinden çok memnunum ben tel taktırdıktan sonra birçok arkadasım da kendisine muayene olmak istedi güler yüzlü güvenilir ve başarılı daha ne istenir. :)",
      time: 1682438236,
      translated: false,
    },
    {
      author_name: "serkan üçpınar",
      author_url:
        "https://www.google.com/maps/contrib/113660381771308757250/reviews",
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "5 ay önce",
      text: "Emre Bey ve Aslı Hanıma ne kadar teşekkür etsem az. Profesyonel ve müthis insanlar. Gömülü dişim vardı, birde üstüne gülerken alt dişlerim gözüktüğü için fotograf çektirmek istemiyor, her fotografta ağzım kapalıydı. 5 sene doktor aradım ve gözüm korktugu için hep erteledim. Emre Bey güven verdi. Çok sıcak bir ortamları var. 1,5 sene diş teli tedavisi ve hiç ağrı hissetmedigim Emre Bey’in operasyonu ile hayal ettiğim görüntüye kavuştum. Şimdi iyiki diyorum, iyi sizi tanımışım. 🙏",
      time: 1677347446,
      translated: false,
    },
    {
      author_name: "Pınar Bora",
      author_url:
        "https://www.google.com/maps/contrib/116399622435143468389/reviews",
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "bir ay önce",
      text: "Aralık dişlere sahiptim.Emre Bey'e muayene olduktan sonra alt çenemin geri de olduğunu söyledi.Bunun üzerine tel takıldı.Gummy smile'ı yok etmek için mini vidalar takıldı ve tam 1 yıl sonra tedavim bitti.Tedavi esnasında bir sorun yaşamadım.Kendisi çok ilgili,anlayışlı,tedavi esnasında her zaman hastasını bilgilendiren güleryüzlü bir diş hekimi.Ablam da benim memnuniyetim üzerine muayene olup tel takmaya başladı.Şuan için her şey çok güzel ilerliyor.Eşi Aslı Hanım tedavi bitiminde tellerimi çıkartıp temizliğini yapmıştı.Çok güleryüzlü,hastanın isteklerine önem veren bir hekim.Asistanları Yasemin Hanım da her daim yardımcı oldu.Her birine ayrı ayrı teşekkür ederim.",
      time: 1687276875,
      translated: false,
    },
    {
      author_name: "Reyhan Arslan",
      author_url:
        "https://www.google.com/maps/contrib/108477629268032195672/reviews",
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      relative_time_description: "bir ay önce",
      text: "Merhaba öncelikle sabırları için çok teşekkürler kolay bir hasta değildim  fakat sabırla yarım saatlik işlemi öğürtü refleksim olduğu için 1 saatte uygulamak zorunda kaldılar ağız yapım dolayısı ile işlemlerim de biraz zorlu geçti fakat olmayacak işlemler olduruldu, maddi boyutu değil öncelik ağız sağlığı ve hasta memnuniyeti ön planda tutuldu ayrıca sanki daha önceden hep tanışıyormuşsunuz da ziyarete gitmişsiniz gibi karşılandım emekleri  için tekrardan teşekkür ederim",
      time: 1685914911,
      translated: false,
    },
    {
      author_name: "M... M...",
      author_url: null,
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      text: "Üst ön dişlerim alt dişlerinin arkasında çapraz şekilde ısırıyordum. Ayrıca üst çenemde darlık olduğu için arkalar da çaprazdaydı. Bana hep ameliyat olmam gerektiği söylendiği için umudu kesmiştim. Uzaktan bir akrabamın benzer bir problemini çözdüğünü öğrenince Emre hocama muayene oldum. Bana mini vidalarla ameliyatsız tedavi olabileceğimi söyledi. Sadece 14 ay sonra sonuç mükemmel oldu. Eski fotoğraflarıma bakınca farka hala şaşırıyorum. İyi ki sizi bulmuşum. Buradan paylaşmak istedim :)",
      time: 1706724884,
      translated: false,
    },
    {
      author_name: "Se...a",
      author_url: null,
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      text: "2016-2018 de Konya'da Emre hoca tarafından ortodonti tedavisi görmüştüm çok iyi, çok ilgili bir diş hekimiydi dişlerimden hala çok memnunum. Kendisine burdan çok teşekkür ederim.",
      time: 1617214484,
      translated: false,
    },
    {
      author_name: "İ...",
      author_url: null,
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      text: "Emre Hocaya tedavi olan iş arkadaşımın dişlerini çok beğendiğim için ben de kendisine tel taktırdım. Daha ikinci ay ve şimdiden dişlerim hiç olmadığı kadar güzel oldu. Çok memnunum.",
      time: 1601576084,
      translated: false,
    },
    {
      author_name: "H...",
      author_url: null,
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      text: "İki yıl ortodonti tedavisi gördüm çok memnun kaldım. Dişlerim tam istediğim gibi oldu.Hasta taleplerini ve önceliklerini üst seviyede dikkate alan ve tedaviyi buna göre planlayıp uygulayan hekimimize çok teşekkür ederim. İşindeki profesyonelliğini ve yeteneğini anlatmama gerek dahi yok,o derece iyi,sıcakkanlı, sevecen ,ilgili ve her daim bilgi veren yaklaşımı ile vazgeçilmez bir doktor.Özellikle cerrahi işlemler konusunda tereddütü ve korkusu olan hastalar hiç çekinmeden başvurabilirler.",
      time: 1596229200,
      translated: false,
    },
    {
      author_name: "Ç...",
      author_url: null,
      language: "tr",
      original_language: "tr",
      profile_photo_url: null,
      rating: 5,
      text: "Köpek dişimin geride olmasıyla ilgili görüşme sağlamıştım Emre Bey'le. Bunu öne aldırmak istiyordum aslında ama hocanın muayenesi sonucu aslında çenemi kapatışımda da bir yanlışlık olduğunu gördük. Bu sefer tüm dişlerim için bir ortodonti tedavisine başlama kararı aldık. Şimdilik her şey güzel gidiyor, hocamdan da ayrıca çok memnunum. Gerçekten mükemmel bir hekim, iletişimi de bir o kadar başarılı. İşlemlerin hepsini kafasında hesaplıyor ve her şeyi ona göre uyguluyor. Kesinlikle çok memnunum.",
      time: 1593550800,
      translated: false,
    },
  ],
};
